### ISSUE TITLE
Fix hotel link

### ISSUE THREAD

**Issue by chritea** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#100]
The link to the hotel search does not work when no dates are pre selected.

Please update with this link https://www.hotel.de/Search?hs_rooms=1&lng=EN&hs_departure=05%2F05%2F2017&h_persons_total=1&hs_destination=HCC%20Hannover%20Congress%20Centrum%2C%20Theodor-Heuss-Platz%2C%20Hanover%2C%20Germany&hs_arrival=01%2F05%2F2017&LACCode=LEGP-CmRTAAAAoA_HqZ1NcK3UfhS_lUGlZYQLzLsBOhua-PtEwqkobdPaWFJ6BxP0d38n5kdYwagj3LtZeWMXdWaQojO5GW8k9QBmwNUmHtdc1WhKPc5jP_JChiS2yM5zkVl8zoIKoy3TEhCiZoCT0-LGyGSbHsE04F0dGhSOv2Chf4Kj_vlfp0cO6DMv2-p60w

where dates fomr may 1.st.to may 5th. are set.

**Comment by amandadebler** [comment]
And that link is kind of broken for me, because my EN-us defaulted web browser interprets 01/05/17 as 5 January 2017 😆

**Comment by amandadebler** [comment]
@chritea  It works with ISO dates (2017-05-02 and 2017-05-05), so fixed.

**Comment by amandadebler** [comment]
Really fixed :)
