### ISSUE TITLE
Change agenda details

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#106]
Please change the agenda as follows:

Day 3 Track 5 9:45h "ChatOps with PowerShell" is now Day 3 Track 2 9:45h
Day 3 Track 2 9:45h "Visualising performance in VMware vSphere" is now Day 3 Track 2 15:30h
Day 3 Track 2 15:30h "Automation in a hybrid world" is now Day 3 Track 5 8:30h
Day 3 Track 5 8:30h "Azure Automation - Advanced Runbook Design" is now Day 3 Track 5 9:45h

Many thanks!

**Comment by amandadebler** [comment]
Committed to Dev

**Comment by amandadebler** [comment]
Just noticed that that move put two of Luc's sessions in the 15:30 slot on Day 3.

**Comment by amandadebler** [comment]
See where you broke a YAML file by looking at Travis' build history:

![image](https://cloud.githubusercontent.com/assets/12802604/24504016/37572442-155d-11e7-8981-b3c2709e77c2.png)

**Comment by amandadebler** [comment]
Making executive decision to switch Matt Hodgkins' Day 3-Track 2-9:45 with Luc Dekens' Day 3-Track 2-15:30 so that Luc doesn't have two sessions at the same time :)

**Comment by TobiasPSP** [comment]
Amanda, well done.

This slipped. Our agenda is so huge and complex, even apparently minor changes produce issues. Let’s try and not touch it anymore in the future! 😊

 

Many thanks,

Tobias

 

Von: Amanda Debler [mailto:notifications@github.com] 
Gesendet: Donnerstag, 30. März 2017 15:22
An: PowerShellConferenceEU/PowerShellConferenceEU.github.io <PowerShellConferenceEU.github.io@noreply.github.com>
Cc: TobiasPSP <tobias.weltner@scriptinternals.de>; Author <author@noreply.github.com>
Betreff: Re: [PowerShellConferenceEU/PowerShellConferenceEU.github.io] Change agenda details (#106)

 

Making executive decision to switch Matt Hodgkins' Day 3-Track 2-9:45 with Luc Dekens' Day 3-Track 2-15:30 so that Luc doesn't have two sessions at the same time :)

**Comment by amandadebler** [comment]
Checked against EventsXD and committed to master, closing.
