### ISSUE TITLE
Add links to psconf.eu

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#109]
Can you please add these links to psconf.eu (both languages):

Join the delegate slack space, and get to know other delegates so you feel at home when the conference opens: https://psconfeu2017.slack.com/shared_invite/MTY2NDg2NjgxNDU5LTE0OTE2NjQwOTAtYzNiNWQxNTAzMA
Travel Directions: www.psconf.eu/travel.pdf
Conference Information: www.psconf.eu/psconfeu_info.pdf
Venue Floor Plan: www.psconf.eu/floorplan.pdf
Preconference Workshops Info: www.psconf.eu/preconf_workshops.pdf
Download the eventsXD conference app: http://www.eventsxd.com/download

Many thanks!

**Comment by amandadebler** [comment]
On it - where on the page do you guys think that stuff should go? Towards the top, or after the registration form?

**Comment by TobiasPSP** [comment]
Towards the top 👍

Von meinem iPhone gesendet

**Comment by amandadebler** [comment]
Done
