### ISSUE TITLE
Add a box with this text

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#110]
Use PowerShell to view and search the most current version of our conference agenda! Run this:
 (iwr powershell.love -UseB).Content.SubString(1) | ConvertFrom-Json | %{$_} | ogv 
Participate in our grand Agenda Competition! Details: http://www.powertheshell.com/agendacompetition/

**Comment by amandadebler** [comment]
Added as ExtraInfo box
