### ISSUE TITLE
Issues with the new links on psconf.eu

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#113]
Great job adding the links! Here are some minor issues:

Link  http://www.powertheshell.com/agendacompetition/  on psconf.eu  does not work because it links to "http://www.psconf.eu/%22http://www.powertheshell.com/agendacompetition//%22". Please change to: http://www.powertheshell.com/agendacompetition 

In addition, to make the link section more readable, can you change these things:

In the yellow box, please do not insert a line break before "Details". Instead, have "Details..." be in the same line with the previous text.

"Useful Documents" needs a ":" at the end. Would it be possible to use a different bullet for the subitems? If this is not possible, can the subitems have no bullet point?

Many thanks!

**Comment by amandadebler** [comment]
I think I can force subitems to have a circle... not sure why @rdtechie's last change didn't work, because it looks fine to me.

Will look at it again.

**Comment by rdtechie** [comment]
Thanks. Maybe because I didn't use the correct way to create a pull request? Anyway, Tobias also described the problem, so I think you have more luck to correct it. :)

**Comment by TobiasPSP** [comment]
Looks awesome!

 

Von: Richard Diphoorn [mailto:notifications@github.com] 
Gesendet: Montag, 10. April 2017 12:22
An: PowerShellConferenceEU/PowerShellConferenceEU.github.io <PowerShellConferenceEU.github.io@noreply.github.com>
Cc: TobiasPSP <tobias.weltner@scriptinternals.de>; Author <author@noreply.github.com>
Betreff: Re: [PowerShellConferenceEU/PowerShellConferenceEU.github.io] Issues with the new links on psconf.eu (#113)

 

Thanks. Maybe because I didn't use the correct way to create a pull request? Anyway, Tobias also described the problem, so I think you have more luck to correct it. :)

**Comment by amandadebler** [comment]
Fulfilled by #114
