### ISSUE TITLE
SystemFrontier sponsor logo is too small

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#118]
The "SystemFrontier" logo in the sponsors section is very small, and almost unreadable on mobile devices. Can we make it double the size?

**Comment by amandadebler** [comment]
Sure - I'll check the scaling for xs/s (looked right on desktop + pad)

**Comment by amandadebler** [comment]
For future reference: I need to change the Bootstrap spacing so that there are only two columns of logos on s and xs displays, and 3 on m and l

**Comment by amandadebler** [comment]
Fixed in Commit #120 ; changed column sizes for small screens
