### ISSUE TITLE
Venue pictures are distorted

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#119]
The pictures of the venue used to be in a neat matrix. They are now huge, and seem to be unordered. Something must have gone amiss with the image style. Anyone a clue?

**Comment by amandadebler** [comment]
Please post a screenshot.

**Comment by amandadebler** [comment]
Here's what I currently see on www.psconf.eu in Firefox (MacOS), browser covering most of screen:

<img width="1185" alt="screen shot 2017-04-25 at 00 23 50" src="https://cloud.githubusercontent.com/assets/12802604/25361285/aff1144a-294d-11e7-95f7-73534d8e2b15.png">

It retains proportion when I reduce it to 1/3 of the screen:

<img width="600" alt="screen shot 2017-04-25 at 00 27 52" src="https://cloud.githubusercontent.com/assets/12802604/25361368/154c1c22-294e-11e7-881d-1f21b1dec816.png">

What device/browser are you seeing the problem in?

**Comment by stuartpreston** [comment]
Closing this due to age. Will take into consideration for this year's site.
