### ISSUE TITLE
Move current content to a 2016 page and start thinking of prep reqs for 2017

### ISSUE THREAD

**Issue by kilasuit** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#39]
Looking ahead we need to "archive" the 2016 page and look to rebrand a little for 2017 conference

This is really a Placeholder issue so that I dont forget about it though @gravejester we will need to catch up on this some point in September.

**Comment by gravejester** [comment]
Yep, good point. :)

**Comment by gravejester** [comment]
Copied old site into separate 2016 repository, and started updating meta-data to reflect the update to 2017 conference.
