### ISSUE TITLE
add PSConfEU logo as favicon

### ISSUE THREAD

**Issue by gaelcolas** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#42]
I think it'd be neat to add the psconfeu logo, that would add branding (which would be good for us and for sponsors).
I found that http://www.favicon-generator.org/ has a nice way to generate the favicons, different size, link rel, meta tag and so on.

**Comment by gravejester** [comment]
Conference logo should already be present as favicon, but will likely not show on the dev-site. Please let me know if you can't see the icon when the updated site goes live.
