### ISSUE TITLE
Add in link to 2016 site on the Navigation

### ISSUE THREAD

**Issue by kilasuit** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#43]
Allows simple navigation to see last years's event

Will require adding 2017 to the navigation as well on the 2016 site

**Comment by gravejester** [comment]
The 2016 site is not view-able as a website, so don't see the point in adding a link to the GitHub repo. It would also clutter up the nav for people viewing the site on a mobile.

What we could do though, is to link to the 2016 GitHub repo somewhere in the footer?

**Comment by kilasuit** [comment]
It should be accessible via http://www.psconf.eu/2016/ from the way it has been setup

**Comment by gravejester** [comment]
Hmm.. I didn't know that :)
