### ISSUE TITLE
Change Typography

### ISSUE THREAD

**Issue by rdtechie** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#44]
The font used on the website seems a bit outdated to me. I would suggest to use Open Sans, size 18pts.

**Comment by gravejester** [comment]
I agree we could use with a more updated font, I'll try Open Sans. I quite like the font Troy Hunt uses on his blog - Vollkorn - as well: https://www.troyhunt.com/

**Comment by rdtechie** [comment]
To be honest, I don't like that font. It looks chaotic to me. Troy has good content, but the design skills are a bit bad. ;) I really like the font coolblue.nl is using. It's also Open Sans. Here's an example. Forgive me, it's in Dutch but very readable: http://blog.coolblue.nl/geen-bakprinses-zo-lukt-het-je-wel
