### ISSUE TITLE
Fresh Pictures for psconf.eu 2017

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#50]
Attached please find a ZIP with a collection of pics taken from 2016 conf. One is from Richard, one from Christian, both on our team.

Can you add some of them to the new website to show the conference spirit? Can we use the picture with the pink girls for the registration section?
[psconf16_pic_amaterials.zip](https://github.com/PowerShellConferenceEU/PowerShellConferenceEU.github.io/files/560360/psconf16_pic_amaterials.zip)

**Comment by gravejester** [comment]
Replaced some of the old pictures with new ones.
