### ISSUE TITLE
German submission confirmation text

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#59]
Ihre Registrierung für die psconf.eu 2017 war erfolgreich!
Vielen Dank, wir freuen uns auf Sie! Sie werden innerhalb der nächsten 24h von uns die Teilnahmerechnung erhalten - falls nicht, überprüfen SIe bitte Ihren Spam-Ordner oder melden sich bei uns.

Ihre Plätze sind für die nächsten 30 Tage fest reserviert. Bitte bezahlen Sie die Rechnung innerhalb dieser 30 Tage, um die Registrierung abzuschließen. Sie erhalten nach Zahlungseingang eine verbindliche Teilnahmebestätigung.

Falls der Zahlungslauf in Ihrem Unternehmen länger dauert als 30 Tage, teilen Sie uns dies bitte kurz mit.

Der nächste Schritt: kümmern Sie sich um Ihre Hotelübernachtungen. Warten Sie besser nicht allzu lange. Noch ist die Auswahl groß und die Angebote preiswert.

Sie finden aktualisierte Informationen auf psconf.eu. Bitte schauen Sie hin und wieder für die aktuellsten Informationen vorbei. Oder folgen Sie uns auf twitter: #psconfeu.

**Comment by gravejester** [comment]
Done
