### ISSUE TITLE
Additional pictures for the website.

### ISSUE THREAD

**Issue by rdtechie** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#61]
Guys, here are some extra pictures that I took during last conference. Use them where you want. [https://rdiphoorn.stackstorage.com/s/ZBH9ZmPt5GXk9wy?dir=](url)

**Comment by TobiasPSP** [comment]
can we add them to the pic gallery?

**Comment by amandadebler** [comment]
Working on a second FlowGallery to post candids

**Comment by amandadebler** [comment]
But it might be easier to use the native Bootstrap photo grid - and generate the YAML with PS...
