### ISSUE TITLE
Speaker Picture Will Anderson

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#76]
Please add the attached picture for speaker "Will Anderson". He currently has a blank pic.
![willanderson](https://cloud.githubusercontent.com/assets/20953725/22430614/21781d38-e70f-11e6-8ce3-663625a5b4da.jpg)

**Comment by gravejester** [comment]
Not the best picture (low resolution), but added to Dev
