### ISSUE TITLE
Speaker picture Daniel Both

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#78]
Please add "Daniël
![danielboth_photo_small](https://cloud.githubusercontent.com/assets/20953725/22455542/6c8b90c4-e78d-11e6-88ef-b8f2af54433d.jpg)
 Both" to the speakers section.
Bio:
Daniël is an Infrastructure Engineer with 10 years of experience in IT. Started with scripting in batch and VBScript, but soon adapted PowerShell and loving it since. He’s currently working @ Optiver where he manages the storage, hypervisor and Windows infrastructure with the goal to serve the business best by automating as much as possible.

**Comment by gravejester** [comment]
Is he from Germany?
