### ISSUE TITLE
Add Speaker Angel Calvo

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#79]
![angelcalvo](https://cloud.githubusercontent.com/assets/20953725/22514821/d4e32b5a-e8a0-11e6-89a7-983aaf974980.jpg)

Bio:

Angel Calvo (twitter: @angelcalvos) is a Partner Group Program Manager for Microsoft Azure Operations Management Suite (OMS).  Angel is also the Community Product Lead for the PowerShell Open Source GitHub Projects:  http://github.com/powershell 

In his current role, Angel Calvo is responsible to drive the business and technology strategies, and leads the Program Management team responsible for delivering:  The Azure OMS Configuration and Automation Service portfolio;  PowerShell and DSC on Linux and Windows; Windows Remote Management Protocol (WinRM); OpenSSH for Windows; and the automation Platform that enables IT Professionals, DevOps and Hosters to configure and manage: Azure Services, Windows, OMS Solutions, Hybrid Clouds and Data Center infrastructures.

Angel joined Microsoft in 1991 in the company’s PC Mai / Exchange Server engineering team. Since then, Angel has had the opportunity to work in a variety of engineering roles, products and services across Microsoft. Including five years as Engineering Manager for MSN services, four years as Group Program Manager in Office SharePoint team, four years as Product Unit Manager for the Azure Global Foundation Service Engineering team and more recently four years as Director of Engineering for the Windows Server Cloud Infrastructure team responsible for delivering PowerShell and DSC.

Angel is native from Madrid, Spain. Angel went to school to the University Laboral of Toledo, Spain, and outside work Angel’s other passions are Scuba Diving, Photographic and Playing Guitar.

**Comment by gravejester** [comment]
Added new speaker to Dev
