### ISSUE TITLE
Add new sponsor

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#80]
Please add the Manning sponsor logo, and link it to http://www.manning.com!

**Comment by TobiasPSP** [comment]
![manning logo_color](https://cloud.githubusercontent.com/assets/20953725/22540786/90c8ca24-e922-11e6-8548-c46a0ca9628d.png)

**Comment by gravejester** [comment]
New sponsor added to Dev.
