### ISSUE TITLE
Add Picture for Raimund Andree

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#86]
![raimund](https://cloud.githubusercontent.com/assets/20953725/22945458/9643a920-f2f4-11e6-9878-b38e3c1059b5.jpg)

**Comment by gaelcolas** [comment]
Was done in #85. Will show up when Dev is merged to master. (link to image is www.psconfeu.io so not working with dev site).
