### ISSUE TITLE
Change order for speakers section and agenda

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#90]
Can we show the agenda before the speakers section?
The agenda is relatively small in height whereas the speakers section is huge. It would make navigation easier if the agenda was showing first, then the speakers section.

**Comment by amandadebler** [comment]
Done, along with moving some of the sessions around to match the HTML grid you sent me.

**Comment by TobiasPSP** [comment]
Perfect, I am now adding the PS team member sessions and do some polishing, then we should be set.

Many thanks Amanda!

 

Von: Amanda Debler [mailto:notifications@github.com] 
Gesendet: Donnerstag, 16. Februar 2017 23:52
An: PowerShellConferenceEU/PowerShellConferenceEU.github.io <PowerShellConferenceEU.github.io@noreply.github.com>
Cc: TobiasPSP <tobias.weltner@scriptinternals.de>; Author <author@noreply.github.com>
Betreff: Re: [PowerShellConferenceEU/PowerShellConferenceEU.github.io] Change order for speakers section and agenda (#90)

 

Done, along with moving some of the sessions around to match the HTML grid you sent me.
