### ISSUE TITLE
List PS Team and MVP's higher in the speakers section

### ISSUE THREAD

**Issue by kilasuit** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#91]
It's mainly more important for the PS Team members to be listed towards the top of the speakers section but could we also make them stand out somehow?

**Comment by TobiasPSP** [comment]
We want all speakers to be the same. Let's not decorate someone, neither MSFT nor MVP. We are all in this together ;-) If you'd like, we could sort the speakers alphabetically.
