### ISSUE TITLE
Label Speaker Pics

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#94]
Ryan suggested highlighting some speakers. That's a good idea.
What if we added a symbol or a text label for Microsoft employees and for active MVPs?
I would not think we should order the speakers by these labels but highlighting their special status would be awesome and illustrate how many of these are actually speaking.

**Comment by amandadebler** [comment]
Maybe a little square Microsoft logo, like we did the flags for speaker sessions?

**Comment by amandadebler** [comment]
Cut the logo down to various sizes and added to Dev branch (16x16, 24x24, and 32x32, as well as full size original)

**Comment by amandadebler** [comment]
@PowerShellConferenceEU/owners  Do we still want to do this?

**Comment by stuartpreston** [comment]
Closing this due to age. We'll definitely consider highlighting some of the early speakers that are confirmed this year.
