### ISSUE TITLE
Please Add Speaker Pic for James ONeill

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#98]
Here it is:
![jamesoneill](https://cloud.githubusercontent.com/assets/20953725/23404099/7e55bf14-fdb3-11e6-9edd-2914acae815c.jpg)

**Comment by amandadebler** [comment]
@TobiasPSP Do you have an uncropped version? This one is square, not 3:2 - our gallery plays nicer when the photos are 300x200.

**Comment by kilasuit** [comment]
I have emailed James to request a rectangular photo for the site and once this comes through I'll get this updated.

**Comment by kilasuit** [comment]
this is now over a year old - closing as should no longer be an issue
